<script lang="ts">
import type { PrimitiveProps } from '@/Primitive'

export interface FieldControlProps extends PrimitiveProps {
  /** Id of the element. Falls back to the id generated by the ancestor `FieldRoot`. */
  id?: string
}
</script>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, useAttrs } from 'vue'
import { Primitive } from '@/Primitive'
import { useForwardExpose } from '@/shared'
import { injectFieldRootContext } from './FieldRoot.vue'

defineOptions({
  inheritAttrs: false,
})

const props = withDefaults(defineProps<FieldControlProps>(), {
  as: 'input',
})

const fieldContext = injectFieldRootContext()
const attrs = useAttrs()

const { forwardRef, currentElement } = useForwardExpose()

const controlId = computed(() => props.id ?? fieldContext.fieldId.value)

// Merge, don't overwrite: a consumer-provided `aria-describedby` is combined
// with the ids accumulated from `FieldDescription`/`FieldError`.
const restAttrs = computed(() => {
  const { 'aria-describedby': _omit, ...rest } = attrs
  return rest
})
const mergedDescribedBy = computed(() => {
  const consumerValue = attrs['aria-describedby'] as string | undefined
  return [consumerValue, fieldContext.describedBy.value].filter(Boolean).join(' ') || undefined
})

function getElement() {
  return currentElement.value as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement | undefined
}

function handleFocus() {
  fieldContext.handleControlFocus()
}
function handleBlur() {
  fieldContext.handleControlBlur(getElement())
}
function handleInput() {
  fieldContext.handleControlInput(getElement())
}

onMounted(() => {
  fieldContext.setControlElement(currentElement.value as HTMLElement | undefined)
})
onBeforeUnmount(() => {
  fieldContext.setControlElement(undefined)
})
</script>

<template>
  <Primitive
    :id="controlId"
    :ref="forwardRef"
    v-bind="restAttrs"
    :as="as"
    :as-child="asChild"
    :name="fieldContext.name.value"
    :disabled="fieldContext.disabled.value || undefined"
    :required="fieldContext.required.value || undefined"
    :aria-describedby="mergedDescribedBy"
    :aria-invalid="fieldContext.invalid.value || undefined"
    @focus="handleFocus"
    @blur="handleBlur"
    @input="handleInput"
  >
    <slot />
  </Primitive>
</template>
