<script lang="ts">
import type { PrimitiveProps } from '@/Primitive'

export interface FieldControlProps extends PrimitiveProps {
  /** Id of the element. Falls back to the id generated by the ancestor `FieldRoot`. */
  id?: string
}
</script>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, useAttrs } from 'vue'
import { Primitive } from '@/Primitive'
import { useForwardExpose } from '@/shared'
import { injectFieldRootContext } from './FieldRoot.vue'

defineOptions({
  inheritAttrs: false,
})

const props = withDefaults(defineProps<FieldControlProps>(), {
  as: 'input',
})

const fieldContext = injectFieldRootContext()
const attrs = useAttrs()

const { forwardRef, currentElement } = useForwardExpose()

const controlId = computed(() => props.id ?? fieldContext.fieldId.value)

// A boolean attribute is present unless omitted or explicitly `false`
// (`<FieldControl required>` passes `''`).
function isAttrSet(value: unknown) {
  return value !== undefined && value !== false && value !== 'false'
}

// The field's `name` takes precedence; `disabled`/`required` apply when set on
// either the field or the control. The rest of the consumer's attributes pass
// through untouched.
const name = computed(() => fieldContext.name.value ?? attrs.name as string | undefined)
const disabled = computed(() => fieldContext.disabled.value || isAttrSet(attrs.disabled))
const required = computed(() => fieldContext.required.value || isAttrSet(attrs.required))

const restAttrs = computed(() => {
  const { 'aria-describedby': _describedBy, 'aria-invalid': _invalid, 'name': _name, 'disabled': _disabled, 'required': _required, ...rest } = attrs
  return rest
})

// Merge, don't overwrite: a consumer-provided `aria-describedby` is combined
// with the ids accumulated from `FieldDescription`/`FieldError`.
const mergedDescribedBy = computed(() => {
  const consumerValue = attrs['aria-describedby'] as string | undefined
  return [consumerValue, fieldContext.describedBy.value].filter(Boolean).join(' ') || undefined
})

// A consumer-provided `aria-invalid` always wins.
const ariaInvalid = computed(() => attrs['aria-invalid'] ?? (fieldContext.invalid.value || undefined))

type NativeControl = HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement

function getElement() {
  const element = currentElement.value as HTMLElement | undefined
  return element && ['INPUT', 'TEXTAREA', 'SELECT'].includes(element.tagName)
    ? element as NativeControl
    : undefined
}

let unregister: (() => void) | undefined
onMounted(() => {
  unregister = fieldContext.registerControl({
    element: () => currentElement.value as HTMLElement | undefined,
    // Always read the live DOM value: programmatic writes (a direct `.value`
    // assignment, autofill) don't fire `input`.
    getValue: () => getElement()?.value,
    validityElement: getElement,
  })
})
onBeforeUnmount(() => unregister?.())
</script>

<template>
  <Primitive
    :id="controlId"
    :ref="forwardRef"
    v-bind="restAttrs"
    :as="as"
    :as-child="asChild"
    :name="name"
    :disabled="disabled || undefined"
    :required="required || undefined"
    :aria-describedby="mergedDescribedBy"
    :aria-invalid="ariaInvalid"
    @focus="fieldContext.handleControlFocus()"
    @blur="fieldContext.handleControlBlur()"
    @input="fieldContext.handleControlInput()"
  >
    <slot />
  </Primitive>
</template>
