import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Component families that get their own subpath export (`reka-ui/dialog`, …).
 *
 * The root barrel (`src/index.ts`) is the single source of truth for what is public:
 * every `export … from './<Family>'` statement in it that re-exports at least one
 * runtime value becomes a subpath, exposing exactly what the barrel exposes for that
 * family. Families the barrel does not export (Collection, Popper, Menu, …) get none.
 *
 * Based on the approach from https://github.com/unovue/reka-ui/pull/2764.
 */

const PACKAGE_DIR = join(dirname(fileURLToPath(import.meta.url)), '..')
const BARREL_PATH = join(PACKAGE_DIR, 'src/index.ts')
/** Generated (git-ignored) entry modules for families the barrel only partially exports. */
export const GENERATED_ENTRIES_DIR = '.entries'

const FAMILY_EXPORT = /^export\s+(\*|(?:type\s+)?\{[^}]*\})\s+from\s+'\.\/([A-Z]\w*)'/gm
const CAMEL_BOUNDARY = /([a-z0-9])([A-Z])/g
const ACRONYM_BOUNDARY = /([A-Z]+)([A-Z][a-z])/g
const TYPE_SPECIFIER = /^type\s/

export interface ComponentFamily {
  /** PascalCase source directory name, e.g. `AlertDialog`. */
  name: string
  /** kebab-case subpath key, e.g. `alert-dialog` (imported as `reka-ui/alert-dialog`). */
  key: string
  /** Build entry, relative to the package root. */
  entry: string
  /**
   * Source of the generated entry module. Only set when the barrel re-exports a subset
   * of `src/<Family>/index.ts`, so the subpath cannot point at the family index directly.
   */
  generatedSource?: string
}

/**
 * The package is ESM-only, so `types` is nested under `import` like the JavaScript:
 * a `require()` resolves neither, the same as the hand-written entries.
 */
export interface SubpathExport {
  import: { types: string, default: string }
}

export function toKebabCase(name: string): string {
  return name
    .replace(CAMEL_BOUNDARY, '$1-$2')
    .replace(ACRONYM_BOUNDARY, '$1-$2')
    .toLowerCase()
}

export function getComponentFamilies(barrel = readFileSync(BARREL_PATH, 'utf8')): ComponentFamily[] {
  const families = new Map<string, ComponentFamily>()

  for (const [, clause, name] of barrel.matchAll(FAMILY_EXPORT)) {
    const key = toKebabCase(name)
    if (families.has(name))
      throw new Error(`[families] "${name}" is exported more than once from src/index.ts, merge the statements`)

    if (clause === '*') {
      families.set(name, { name, key, entry: `./src/${name}/index.ts` })
      continue
    }

    // `export type { … }` or a list made only of `type X` specifiers: nothing to import at runtime
    const specifiers = clause.slice(clause.indexOf('{') + 1, clause.lastIndexOf('}')).split(',').map(i => i.trim()).filter(Boolean)
    if (clause.startsWith('type') || specifiers.every(i => TYPE_SPECIFIER.test(i)))
      continue

    families.set(name, {
      name,
      key,
      entry: `./${GENERATED_ENTRIES_DIR}/${key}.ts`,
      generatedSource: `// Generated by scripts/families.ts from src/index.ts. Do not edit.\nexport { ${specifiers.join(', ')} } from '../src/${name}'\n`,
    })
  }

  return [...families.values()].sort((a, b) => a.key.localeCompare(b.key))
}

/** Writes the generated entry modules to disk. Must run before the build resolves its entries. */
export function writeGeneratedEntries(families = getComponentFamilies()) {
  const dir = join(PACKAGE_DIR, GENERATED_ENTRIES_DIR)
  rmSync(dir, { recursive: true, force: true })
  for (const family of families) {
    if (!family.generatedSource)
      continue
    mkdirSync(dir, { recursive: true })
    writeFileSync(join(dir, `${family.key}.ts`), family.generatedSource)
  }
}

/** `package.json#exports` entries for every family subpath. */
export function getFamilyExports(families = getComponentFamilies()): Record<string, SubpathExport> {
  return Object.fromEntries(families.map(({ key }) => [
    `./${key}`,
    { import: { types: `./dist/${key}.d.ts`, default: `./dist/${key}.js` } },
  ]))
}

/**
 * Merges the family subpaths into an existing `exports` map: hand-written entries keep
 * their position and value, stale family entries are dropped, `./package.json` stays last.
 */
export function mergeExports(
  current: Record<string, unknown>,
  families = getComponentFamilies(),
): Record<string, unknown> {
  const familyExports = getFamilyExports(families)
  // Generated entries are the only ones with a nested `import` condition
  const isGenerated = (value: unknown) =>
    typeof value === 'object' && value !== null && typeof (value as Record<string, unknown>).import === 'object'

  const handWritten = Object.entries(current).filter(([key, value]) => key !== './package.json' && !isGenerated(value))
  for (const [key] of handWritten) {
    if (key in familyExports)
      throw new Error(`[families] subpath "${key}" collides with an existing package.json export`)
  }

  return {
    ...Object.fromEntries(handWritten),
    ...familyExports,
    './package.json': './package.json',
  }
}
