export interface Emoji {
  char: string
  name: string
}

/** Small on purpose — the point is the grid navigation, not the dataset. */
export const emojis: Emoji[] = [
  { char: '😀', name: 'grinning face' },
  { char: '😃', name: 'grinning face with big eyes' },
  { char: '😄', name: 'grinning face with smiling eyes' },
  { char: '😁', name: 'beaming face' },
  { char: '😆', name: 'grinning squinting face' },
  { char: '😅', name: 'grinning face with sweat' },
  { char: '🤣', name: 'rolling on the floor laughing' },
  { char: '😂', name: 'face with tears of joy' },
  { char: '🙂', name: 'slightly smiling face' },
  { char: '🙃', name: 'upside down face' },
  { char: '😉', name: 'winking face' },
  { char: '😊', name: 'smiling face with smiling eyes' },
  { char: '😇', name: 'smiling face with halo' },
  { char: '🥰', name: 'smiling face with hearts' },
  { char: '😍', name: 'smiling face with heart eyes' },
  { char: '🤩', name: 'star struck' },
  { char: '😘', name: 'face blowing a kiss' },
  { char: '😋', name: 'face savoring food' },
  { char: '😜', name: 'winking face with tongue' },
  { char: '🤪', name: 'zany face' },
  { char: '🤨', name: 'face with raised eyebrow' },
  { char: '🧐', name: 'face with monocle' },
  { char: '🤓', name: 'nerd face' },
  { char: '😎', name: 'smiling face with sunglasses' },
  { char: '🥳', name: 'partying face' },
  { char: '😏', name: 'smirking face' },
  { char: '😢', name: 'crying face' },
  { char: '😭', name: 'loudly crying face' },
  { char: '😤', name: 'face with steam from nose' },
  { char: '😡', name: 'enraged face' },
  { char: '🤯', name: 'exploding head' },
  { char: '😱', name: 'face screaming in fear' },
  { char: '🥵', name: 'hot face' },
  { char: '🥶', name: 'cold face' },
  { char: '😴', name: 'sleeping face' },
  { char: '🤒', name: 'face with thermometer' },
  { char: '🤠', name: 'cowboy hat face' },
  { char: '🤖', name: 'robot' },
  { char: '👻', name: 'ghost' },
  { char: '💀', name: 'skull' },
  { char: '👽', name: 'alien' },
  { char: '🎃', name: 'jack o lantern' },
  { char: '👍', name: 'thumbs up' },
  { char: '👎', name: 'thumbs down' },
  { char: '👏', name: 'clapping hands' },
  { char: '🙌', name: 'raising hands' },
  { char: '🙏', name: 'folded hands' },
  { char: '💪', name: 'flexed biceps' },
  { char: '🤝', name: 'handshake' },
  { char: '✌️', name: 'victory hand' },
  { char: '🤞', name: 'crossed fingers' },
  { char: '👋', name: 'waving hand' },
  { char: '❤️', name: 'red heart' },
  { char: '🧡', name: 'orange heart' },
  { char: '💛', name: 'yellow heart' },
  { char: '💚', name: 'green heart' },
  { char: '💙', name: 'blue heart' },
  { char: '💜', name: 'purple heart' },
  { char: '🔥', name: 'fire' },
  { char: '✨', name: 'sparkles' },
  { char: '🎉', name: 'party popper' },
  { char: '🚀', name: 'rocket' },
  { char: '⚡', name: 'high voltage' },
  { char: '🌈', name: 'rainbow' },
  { char: '☕', name: 'hot beverage' },
  { char: '🍕', name: 'pizza' },
  { char: '🍩', name: 'doughnut' },
  { char: '🍎', name: 'red apple' },
  { char: '🐶', name: 'dog face' },
  { char: '🐱', name: 'cat face' },
  { char: '🦊', name: 'fox' },
  { char: '🐢', name: 'turtle' },
]

export const COLUMNS = 8
